server:
  port: 8080

spring:
  application:
    name: medconsult-gateway
  profiles:
    active: local
  config:
    import: optional:nacos:${spring.application.name}.yaml
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: medconsult-ai-service
          uri: lb://medconsult-ai-service
          predicates:
            - Path=/api/v1/**

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
